# Use root/example as user/password credentials
version: '3.1'
services:
  mongo:
    image: mongo:4.4.5
    ports:
      - '27017:27017'
    volumes:
      - ./db/:/opt/db/
    logging:
      driver: json-file
      options:
        max-size: 10m
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
